# AUTOGENERATED BY NBDEV! DO NOT EDIT!

__all__ = ["index", "modules", "custom_doc_links", "git_url"]

index = {}

modules = []

doc_url = "https://fair-fusion.github.io/monitoring/"

git_url = "https://github.com/fair-fusion/monitoring/tree/{branch}/"

def custom_doc_links(name): return None
